### PR TITLE
Lint issues

### PR DESCRIPTION
**Pull request by dholbach**
Small issues found when using the extension.

### CODE REVIEW

**Comment by squillace** [comment]
Daniel, I wanted to keep the Install command out of the visual path because we can't dynamically remove it depending on install state. (Unless you can figure out how I'm mistaken.) If I'm right, and I'll find out, I'd love to merge the lint fixes if you remove the command from the context menu from the PR. 

Possible? In the meanwhile, I've updated it to handle more of the opening/closing issues and now it'll install correctly if it's not there. I still depend upon helm here for now.

**Comment by dholbach** [comment]
To me it looked like `scope.startTask` wasn't actually used any more, so I thought I'd remove it from the config.

**Comment by dholbach** [comment]
I updated the PR to not conflict any more.

Using the command palette and hitting "Scope: Show Progress" gives `command 'scope.startTask' not found`, so it looks like it's safe to remove it.

**Comment by squillace** [comment]
Correct. Detritus. thanks!

**Pull request merged**
